---
- name: Ensure deployment directory exists
  file:
    path: "{{ deployment_location }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Create virtual environment
  command: python3 -m venv venv
  args:
    chdir: "{{ deployment_location }}"
  creates: "{{ deployment_location }}/venv"

- name: Copy application files
  copy:
    src: app.py
    dest: "{{ deployment_location }}/app.py"
    owner: root
    group: root
    mode: '0755'

- name: Install application dependencies
  pip:
    requirements: "{{ deployment_location }}/{{ wheel_file }}"
    virtualenv: "{{ deployment_location }}/venv"

- name: Create systemd service
  template:
    src: example.service.j2
    dest: /etc/systemd/system/example.service

- name: Start and enable application service
  systemd:
    name: example
    state: started
    enabled: yes

